apiVersion: v1  # Defines the API version in Kubernetes.
kind: ConfigMap  # We are creating a ConfigMap resource.
metadata:
  name: nginx-config  # The name of the ConfigMap.
data:  # This section contains key-value pairs for configuration.
  index.html: |  # This key represents a file inside the ConfigMap.
    <!DOCTYPE html>
    <html>
    <head><title>ConfigMap Example</title></head>
    <body>
      <h1>Hello from ConfigMap!</h1>
      <p>This page is served from a ConfigMap.</p>
    </body>
    </html>
