apiVersion: v1  # Defines the Kubernetes API version.
kind: Service  # We are creating a Kubernetes Service.
metadata:
  name: nginx-service  # The name of the Service.
spec:
  type: NodePort  # Exposes the Service externally.
  selector:  # The Service will connect to Pods with this label.
    app: nginx  # This must match the label in the Pod.
  ports:
  - protocol: TCP  # The network protocol used.
    port: 80        # Port inside the cluster.
    targetPort: 80  # Port inside the Pod (Nginx listens here).
    nodePort: 30007 # The external port exposed outside the cluster.
